r"""
  ____           _
 |  _ \ ___   __| |_ __ _   _ _ __ ___
 | |_) / _ \ / _` | '__| | | | '_ ` _ \
 |  __/ (_) | (_| | |  | |_| | | | | | |
 |_|   \___/ \__,_|_|   \__,_|_| |_| |_|

 Copyright 2021 Podrum Team.

 This file is licensed under the GPL v2.0 license.
 The license file is located in the root directory
 of the source code. If not you may not use this file.
"""


from podrum.block.block_manager import block_manager
from podrum.block import blocks
from podrum.command.command_manager import command_manager
from podrum.command import commands
from podrum.event.event_manager import event_manager
from podrum.event import events
from podrum.item.item_manager import item_manager
from podrum.plugin_manager import plugin_manager
from podrum.world.generator_manager import generator_manager
from podrum.world import generators
from podrum.world.provider_manager import provider_manager
from podrum.world import providers
from podrum.world.world_manager import world_manager


class managers:

    def __init__(self, server) -> None:
        self.server = server
        self.block_manager = block_manager(self)
        self.command_manager = command_manager()
        self.item_manager = item_manager(self.server)
        self.plugin_manager = plugin_manager(server)
        self.generator_manager = generator_manager()
        self.provider_manager = provider_manager()
        self.world_manager = world_manager(server)
        self.register_defaults()
    
    # [register_default_blocks]
    # :return: = None
    # Register the default blocks.
    def register_default_blocks(self) -> None:
        self.block_manager.register_block(blocks.Air())
        self.block_manager.register_block(blocks.Bedrock())
        self.block_manager.register_block(blocks.BoneBlock())
        self.block_manager.register_block(blocks.Bookshelf())
        self.block_manager.register_block(blocks.BrewingStand())
        self.block_manager.register_block(blocks.BrownMushroom())
        self.block_manager.register_block(blocks.Cactus())
        self.block_manager.register_block(blocks.Clay())
        self.block_manager.register_block(blocks.CoalBlock())
        self.block_manager.register_block(blocks.CoalOre())
        self.block_manager.register_block(blocks.Cobblestone())
        self.block_manager.register_block(blocks.Cobweb())
        self.block_manager.register_block(blocks.CraftingTable())
        self.block_manager.register_block(blocks.Dandelion())
        self.block_manager.register_block(blocks.DaylightSensor())
        self.block_manager.register_block(blocks.Deadbush())
        self.block_manager.register_block(blocks.DiamondBlock())
        self.block_manager.register_block(blocks.DiamondOre())
        self.block_manager.register_block(blocks.Dirt())
        self.block_manager.register_block(blocks.EmeraldBlock())
        self.block_manager.register_block(blocks.EmeraldOre())
        self.block_manager.register_block(blocks.EndStone())
        self.block_manager.register_block(blocks.EnchantingTable())
        self.block_manager.register_block(blocks.FlowerPot())
        self.block_manager.register_block(blocks.Farmland())
        self.block_manager.register_block(blocks.Fire())
        self.block_manager.register_block(blocks.Glass())
        self.block_manager.register_block(blocks.GlassPane())
        self.block_manager.register_block(blocks.GoldBlock())
        self.block_manager.register_block(blocks.GoldOre())
        self.block_manager.register_block(blocks.Grass())
        self.block_manager.register_block(blocks.Gravel())
        self.block_manager.register_block(blocks.HardenedClay())
        self.block_manager.register_block(blocks.HayBale())
        self.block_manager.register_block(blocks.Ice())
        self.block_manager.register_block(blocks.IronBars())
        self.block_manager.register_block(blocks.IronBlock())
        self.block_manager.register_block(blocks.IronOre())
        self.block_manager.register_block(blocks.LapisBlock())
        self.block_manager.register_block(blocks.LapisOre())
        self.block_manager.register_block(blocks.StillLava())
        self.block_manager.register_block(blocks.FlowingLava())
        self.block_manager.register_block(blocks.LitPumpkin())
        self.block_manager.register_block(blocks.Magma())
        self.block_manager.register_block(blocks.MonsterSpawner())
        self.block_manager.register_block(blocks.Melon())
        self.block_manager.register_block(blocks.MossyCobblestone())
        self.block_manager.register_block(blocks.Mycelium())
        self.block_manager.register_block(blocks.NetherWartBlock())
        self.block_manager.register_block(blocks.NetherBrickBlock())
        self.block_manager.register_block(blocks.NetherQuartzOre())
        self.block_manager.register_block(blocks.Netherrack())
        self.block_manager.register_block(blocks.Noteblock())
        self.block_manager.register_block(blocks.Obsidian())
        self.block_manager.register_block(blocks.PackedIce())
        self.block_manager.register_block(blocks.Podzol())
        self.block_manager.register_block(blocks.Pumpkin())
        self.block_manager.register_block(blocks.Purpur())
        self.block_manager.register_block(blocks.QuartzBlock())
        self.block_manager.register_block(blocks.RedMushroom())
        self.block_manager.register_block(blocks.RedSandstone())
        self.block_manager.register_block(blocks.RedstoneBlock())
        self.block_manager.register_block(blocks.RedstoneLamp())
        self.block_manager.register_block(blocks.RedstoneOre())
        self.block_manager.register_block(blocks.Sand())
        self.block_manager.register_block(blocks.Sandstone())
        self.block_manager.register_block(blocks.SnowBlock())
        self.block_manager.register_block(blocks.SoulSand())
        self.block_manager.register_block(blocks.Sponge())
        self.block_manager.register_block(blocks.StoneBricks())
        self.block_manager.register_block(blocks.Tnt())
        self.block_manager.register_block(blocks.WoodenPlanks())
        self.block_manager.register_block(blocks.StillWater())
        self.block_manager.register_block(blocks.TallGrass())
        self.block_manager.register_block(blocks.SugarCane())
        self.block_manager.register_block(blocks.GlowingObsidian())
        self.block_manager.register_block(blocks.YellowFlower())
        self.block_manager.register_block(blocks.DoublePlant())
        self.block_manager.register_block(blocks.Anvil())
        self.block_manager.register_block(blocks.LilyPad())
        self.block_manager.register_block(blocks.EndStoneBrick())
        self.block_manager.register_block(blocks.SeaLantern())
        self.block_manager.register_block(blocks.InvisibleBedrock())
        self.block_manager.register_block(blocks.WhiteWool())
        self.block_manager.register_block(blocks.OrangeWool())
        self.block_manager.register_block(blocks.MagentaWool())
        self.block_manager.register_block(blocks.LimeWool())
        self.block_manager.register_block(blocks.YellowWool())
        self.block_manager.register_block(blocks.LightBlueWool())
        self.block_manager.register_block(blocks.PinkWool())
        self.block_manager.register_block(blocks.GrayWool())
        self.block_manager.register_block(blocks.LightGrayWool())
        self.block_manager.register_block(blocks.CyanWool())
        self.block_manager.register_block(blocks.PurpleWool())
        self.block_manager.register_block(blocks.BlueWool())
        self.block_manager.register_block(blocks.BrownWool())
        self.block_manager.register_block(blocks.GreenWool())
        self.block_manager.register_block(blocks.RedWool())
        self.block_manager.register_block(blocks.BlackWool())
        self.block_manager.register_block(blocks.Stone())
        self.block_manager.register_block(blocks.Granite())
        self.block_manager.register_block(blocks.PolishedGranite())
        self.block_manager.register_block(blocks.Diorite())
        self.block_manager.register_block(blocks.PolishedDiorite())
        self.block_manager.register_block(blocks.Andesite())
        self.block_manager.register_block(blocks.PolishedAndesite())
        self.block_manager.register_block(blocks.Poppy())
        self.block_manager.register_block(blocks.BlueOrchid())
        self.block_manager.register_block(blocks.OxeyeDaisy())
        self.block_manager.register_block(blocks.AzureBluet())
        self.block_manager.register_block(blocks.WhiteTulip())
        self.block_manager.register_block(blocks.PinkTulip())
        self.block_manager.register_block(blocks.RedTulip())
        self.block_manager.register_block(blocks.OrangeTulip())
        self.block_manager.register_block(blocks.Cornflower())
        self.block_manager.register_block(blocks.LilyOfTheValley())
        self.block_manager.register_block(blocks.Allium())
        self.block_manager.register_block(blocks.WhiteConcretePowder())
        self.block_manager.register_block(blocks.MagentaConcretePowder())
        self.block_manager.register_block(blocks.LightBlueConcretePowder())
        self.block_manager.register_block(blocks.LimeConcretePowder())
        self.block_manager.register_block(blocks.PinkConcretePowder())
        self.block_manager.register_block(blocks.OrangeConcretePowder())
        self.block_manager.register_block(blocks.YellowConcretePowder())
        self.block_manager.register_block(blocks.GrayConcretePowder())
        self.block_manager.register_block(blocks.LightGrayConcretePowder())
        self.block_manager.register_block(blocks.CyanConcretePowder())
        self.block_manager.register_block(blocks.PurpleConcretePowder())
        self.block_manager.register_block(blocks.BlueConcretePowder())
        self.block_manager.register_block(blocks.BrownConcretePowder())
        self.block_manager.register_block(blocks.GreenConcretePowder())
        self.block_manager.register_block(blocks.RedConcretePowder())
        self.block_manager.register_block(blocks.BlackConcretePowder())
        self.block_manager.register_block(blocks.WhiteConcrete())
        self.block_manager.register_block(blocks.MagentaConcrete())
        self.block_manager.register_block(blocks.LightBlueConcrete())
        self.block_manager.register_block(blocks.LimeConcrete())
        self.block_manager.register_block(blocks.PinkConcrete())
        self.block_manager.register_block(blocks.OrangeConcrete())
        self.block_manager.register_block(blocks.YellowConcrete())
        self.block_manager.register_block(blocks.GrayConcrete())
        self.block_manager.register_block(blocks.LightGrayConcrete())
        self.block_manager.register_block(blocks.CyanConcrete())
        self.block_manager.register_block(blocks.PurpleConcrete())
        self.block_manager.register_block(blocks.BlueConcrete())
        self.block_manager.register_block(blocks.BrownConcrete())
        self.block_manager.register_block(blocks.GreenConcrete())
        self.block_manager.register_block(blocks.RedConcrete())
        self.block_manager.register_block(blocks.BlackConcrete())
        self.block_manager.register_block(blocks.WhiteGlazedTerracotta())
        self.block_manager.register_block(blocks.MagentaGlazedTerracotta())
        self.block_manager.register_block(blocks.LightBlueGlazedTerracotta())
        self.block_manager.register_block(blocks.LimeGlazedTerracotta())
        self.block_manager.register_block(blocks.PinkGlazedTerracotta())
        self.block_manager.register_block(blocks.OrangeGlazedTerracotta())
        self.block_manager.register_block(blocks.YellowGlazedTerracotta())
        self.block_manager.register_block(blocks.GrayGlazedTerracotta())
        self.block_manager.register_block(blocks.SilverGlazedTerracotta())
        self.block_manager.register_block(blocks.CyanGlazedTerracotta())
        self.block_manager.register_block(blocks.PurpleGlazedTerracotta())
        self.block_manager.register_block(blocks.BlueGlazedTerracotta())
        self.block_manager.register_block(blocks.BrownGlazedTerracotta())
        self.block_manager.register_block(blocks.GreenGlazedTerracotta())
        self.block_manager.register_block(blocks.RedGlazedTerracotta())
        self.block_manager.register_block(blocks.BlackGlazedTerracotta())
        self.block_manager.register_block(blocks.WhiteStainedGlass())
        self.block_manager.register_block(blocks.MagentaStainedGlass())
        self.block_manager.register_block(blocks.LightBlueStainedGlass())
        self.block_manager.register_block(blocks.LimeStainedGlass())
        self.block_manager.register_block(blocks.PinkStainedGlass())
        self.block_manager.register_block(blocks.OrangeStainedGlass())
        self.block_manager.register_block(blocks.YellowStainedGlass())
        self.block_manager.register_block(blocks.GrayStainedGlass())
        self.block_manager.register_block(blocks.LightGrayStainedGlass())
        self.block_manager.register_block(blocks.CyanStainedGlass())
        self.block_manager.register_block(blocks.PurpleStainedGlass())
        self.block_manager.register_block(blocks.BlueStainedGlass())
        self.block_manager.register_block(blocks.BrownStainedGlass())
        self.block_manager.register_block(blocks.GreenStainedGlass())
        self.block_manager.register_block(blocks.RedStainedGlass())
        self.block_manager.register_block(blocks.BlackStainedGlass())
        self.block_manager.register_block(blocks.WhiteStainedHardenedClay())
        self.block_manager.register_block(blocks.MagentaStainedHardenedClay())
        self.block_manager.register_block(blocks.LightBlueStainedHardenedClay())
        self.block_manager.register_block(blocks.LimeStainedHardenedClay())
        self.block_manager.register_block(blocks.PinkStainedHardenedClay())
        self.block_manager.register_block(blocks.OrangeStainedHardenedClay())
        self.block_manager.register_block(blocks.YellowStainedHardenedClay())
        self.block_manager.register_block(blocks.GrayStainedHardenedClay())
        self.block_manager.register_block(blocks.LightGrayStainedHardenedClay())
        self.block_manager.register_block(blocks.CyanStainedHardenedClay())
        self.block_manager.register_block(blocks.PurpleStainedHardenedClay())
        self.block_manager.register_block(blocks.BlueStainedHardenedClay())
        self.block_manager.register_block(blocks.BrownStainedHardenedClay())
        self.block_manager.register_block(blocks.GreenStainedHardenedClay())
        self.block_manager.register_block(blocks.RedStainedHardenedClay())
        self.block_manager.register_block(blocks.BlackStainedHardenedClay())
        self.block_manager.register_block(blocks.WhiteStainedGlassPane())
        self.block_manager.register_block(blocks.MagentaStainedGlassPane())
        self.block_manager.register_block(blocks.LightBlueStainedGlassPane())
        self.block_manager.register_block(blocks.LimeStainedGlassPane())
        self.block_manager.register_block(blocks.PinkStainedGlassPane())
        self.block_manager.register_block(blocks.OrangeStainedGlassPane())
        self.block_manager.register_block(blocks.YellowStainedGlassPane())
        self.block_manager.register_block(blocks.GrayStainedGlassPane())
        self.block_manager.register_block(blocks.LightGrayStainedGlassPane())
        self.block_manager.register_block(blocks.CyanStainedGlassPane())
        self.block_manager.register_block(blocks.PurpleStainedGlassPane())
        self.block_manager.register_block(blocks.BlueStainedGlassPane())
        self.block_manager.register_block(blocks.BrownStainedGlassPane())
        self.block_manager.register_block(blocks.GreenStainedGlassPane())
        self.block_manager.register_block(blocks.RedStainedGlassPane())
        self.block_manager.register_block(blocks.BlackStainedGlassPane())
        self.block_manager.register_block(blocks.Fern())
        self.block_manager.register_block(blocks.WetSponge())
        self.block_manager.register_block(blocks.LitRedstoneLamp())
        self.block_manager.register_block(blocks.OakLeaves())
        self.block_manager.register_block(blocks.JungleLeaves())
        self.block_manager.register_block(blocks.DarkOakLeaves())
        self.block_manager.register_block(blocks.AcaciaLeaves())
        self.block_manager.register_block(blocks.SpruceLeaves())
        self.block_manager.register_block(blocks.Deepslate())
        self.block_manager.register_block(blocks.BirchLeaves())
        self.block_manager.register_block(blocks.DeepslateIronOre())
        self.block_manager.register_block(blocks.DeepslateGoldOre())
        self.block_manager.register_block(blocks.DeepslateLapisOre())
        self.block_manager.register_block(blocks.DeepslateRedstoneOre())
        self.block_manager.register_block(blocks.LitDeepslateRedstoneOre())
        self.block_manager.register_block(blocks.DeepslateDiamondOre())
        self.block_manager.register_block(blocks.DeepslateEmeraldOre())
        self.block_manager.register_block(blocks.LitRedstoneOre())
        self.block_manager.register_block(blocks.OakSapling())
        self.block_manager.register_block(blocks.SpruceSapling())
        self.block_manager.register_block(blocks.BirchSapling())
        self.block_manager.register_block(blocks.JungleSapling())
        self.block_manager.register_block(blocks.AcaciaSapling())
        self.block_manager.register_block(blocks.DarkOakSapling())
        self.block_manager.register_block(blocks.Prismarine())
        self.block_manager.register_block(blocks.DarkPrismarine())
        self.block_manager.register_block(blocks.PrismarineBricks())
        self.block_manager.register_block(blocks.OakLog())
        self.block_manager.register_block(blocks.SpruceLog())
        self.block_manager.register_block(blocks.BirchLog())
        self.block_manager.register_block(blocks.JungleLog())
        self.block_manager.register_block(blocks.AcaciaLog())
        self.block_manager.register_block(blocks.DarkOakLog())
        self.block_manager.register_block(blocks.CrimsonStem())
        self.block_manager.register_block(blocks.WarpedStem())
        self.block_manager.register_block(blocks.StrippedOakLog())
        self.block_manager.register_block(blocks.StrippedSpruceLog())
        self.block_manager.register_block(blocks.StrippedBirchLog())
        self.block_manager.register_block(blocks.StrippedJungleLog())
        self.block_manager.register_block(blocks.StrippedAcaciaLog())
        self.block_manager.register_block(blocks.StrippedDarkOakLog())
        self.block_manager.register_block(blocks.StrippedCrimsonStem())
        self.block_manager.register_block(blocks.StrippedWarpedStem())
        self.block_manager.register_block(blocks.OakWoodPlanks())
        self.block_manager.register_block(blocks.SpruceWoodPlanks())
        self.block_manager.register_block(blocks.BirchWoodPlanks())
        self.block_manager.register_block(blocks.JungleWoodPlanks())
        self.block_manager.register_block(blocks.AcaciaWoodPlanks())
        self.block_manager.register_block(blocks.DarkOakWoodPlanks())
        self.block_manager.register_block(blocks.CrimsonPlanks())
        self.block_manager.register_block(blocks.WarpedPlanks())
        self.block_manager.register_block(blocks.WarpedWartBlock())
        self.block_manager.register_block(blocks.RedSand())
        self.block_manager.register_block(blocks.StoneCutter())
        self.block_manager.register_block(blocks.Chest())
        self.block_manager.register_block(blocks.TrappedChest())
        self.block_manager.register_block(blocks.EnderChest())
        self.block_manager.register_block(blocks.EndPortalFrame())
        self.block_manager.register_block(blocks.Cake())

    # [register_default_commands]
    # :return: = None
    # Registers the default commands.
    def register_default_commands(self) -> None:
        self.command_manager.register(commands.debug_command(self.server))
        self.command_manager.register(commands.help_command(self.server))
        self.command_manager.register(commands.plugins_command(self.server))
        self.command_manager.register(commands.reload_command(self.server))
        self.command_manager.register(commands.say_command(self.server))
        self.command_manager.register(commands.stop_command(self.server))
        self.command_manager.register(commands.tell_command(self.server))
        self.command_manager.register(commands.version_command(self.server))
        self.command_manager.register(commands.kick_command(self.server))
        self.command_manager.register(commands.list_command(self.server))
        self.command_manager.register(commands.me_command(self.server))
        self.command_manager.register(commands.seed_command(self.server))
        self.command_manager.register(commands.gamemode_command(self.server))
        self.command_manager.register(commands.time_command(self.server))
        self.command_manager.register(commands.weather_command(self.server))
        self.command_manager.register(commands.difficulty_command(self.server))
    
    # [register_default_events]
    # :return: = None
    # Registers the default events.
    def register_default_events(self) -> None:
        event_manager.register_event(events.player_join_event)
        event_manager.register_event(events.player_move_event)
        event_manager.register_event(events.player_quit_event)
        event_manager.register_event(events.player_sneak_event)
        event_manager.register_event(events.player_sprint_event)
        event_manager.register_event(events.player_jump_event)
        event_manager.register_event(events.player_chat_event)
        event_manager.register_event(events.player_form_response_event)
        event_manager.register_event(events.player_open_inventory_event)
        event_manager.register_event(events.player_close_inventory_event)
    
    # [register_default_items]
    # :return: = None
    # Registers the default items.
    def register_default_items(self) -> None:
        pass
    
    # [register_default_generators]
    # :return: = None
    # Registers the default generators.
    def register_default_generators(self) -> None:
        self.generator_manager.register_generator(generators.flat())
        self.generator_manager.register_generator(generators.void())
        self.generator_manager.register_generator(generators.default())
    
    # [register_default_providers]
    # :return: = None
    # Registers the default providers.
    def register_default_providers(self) -> None:
        self.provider_manager.register_provider(providers.anvil)
        self.provider_manager.register_provider(providers.pm_anvil)
        
    
    # [register_defaults]
    # :return: = None
    # Registers all the defaults.
    def register_defaults(self) -> None:
        self.register_default_blocks()
        self.register_default_commands()
        self.register_default_events()
        self.register_default_items()
        self.register_default_generators()
        self.register_default_providers()
